const actionTypes = {
    LOGOUT: "LOGOUT",

    GET_RHS: "GET_RHS",
    GET_RHS_LIMIT: "GET_RHS_LIMIT",
    GET_RHS_BY_USER: "GET_RHS_BY_USER",
    GET_NEW_RH: "GET_NEW_RH",
    GET_PRICES: "GET_PRICES",
    GET_AREAS: "GET_AREAS",
    GET_NEW_POST: "GET_NEW_POST",
    GET_DISTRICT: "GET_DISTRICT",

    GET_TRANSACTION_TYPES: "GET_TRANSACTION_TYPES",
    GET_REAL_HOME_TYPES: "GET_REAL_HOME_TYPES",
    GET_REAL_HOME_TYPES_BY_TRANS: "GET_REAL_HOME_TYPES_BY_TRANS",

    // USER
    GET_USER: "GET_USER",
    GET_DETAIL_POST: "GET_DETAIL_POST",
    RH_EDIT: "RH_EDIT",
    DEL_DATA_EDIT: "DEL_DATA_EDIT",
};

export default actionTypes;
