const actionTypes = {
    // LOGIN: "LOGIN",
    // REGISTER_SUCCESS: "REGISTER_SUCCESS",
    // REGISTER_FAIL: "REGISTER_FAIL",
    // LOGOUT: "LOGOUT",
    // LOGIN_SUCCESS: "LOGIN_SUCCESS",
    // LOGIN_FAIL: "LOGIN_FAIL",

    GET_RHS: "GET_RHS",
    GET_RHS_LIMIT: "GET_RHS_LIMIT",
    GET_NEW_RH: "GET_NEW_RH",
    GET_PRICES: "GET_PRICES",
    GET_AREAS: "GET_AREAS",
    GET_NEW_POST: "GET_NEW_POST",
    GET_TRANSACTION_TYPES: "GET_TRANSACTION_TYPES",

    GET_REAL_HOME_TYPES: "GET_REAL_HOME_TYPES",
    GET_PROVINCES: "GET_PROVINCES",

    // USER
    GET_CURRENT: "GET_CURRENT",
};

export default actionTypes;
